### ISSUE TITLE
Rabet Login Not Working

### ISSUE THREAD

**Issue by Farabi87** [SpeedOut-Source/BlockLancer#16] opened 2024-10-10 00:07 UTC
Steps to Reproduce:
Install the Rabet extension in the browser.
Create an account in Rabet.
Navigate to BlockLancer and select the Rabet login option.
Expected Behavior: The user should be able to successfully log in using the Rabet extension.
Actual Behavior: The login fails without any error message.
Device: Asus Rog Strix laptop
Browser: Chrome 
![Screenshot_2](https://github.com/user-attachments/assets/270af3c5-772c-4b15-a9bf-b9c2211252e7)

**Comment by arnob016** [comment] 2024-10-10 06:57
Duplicate of an issue reported by same issuer .

**Closed as completed by arnob016** 2024-10-10 06:57 UTC
Labels: invalid
