### ISSUE TITLE
Google Authentication Error

### ISSUE THREAD

**Issue by Farabi87** [SpeedOut-Source/BlockLancer#17] opened 2024-10-10 00:08 UTC
Steps to Reproduce:
Navigate to BlockLancer.
Click on the Google login option.
Attempt to log in using a Google account.
Expected Behavior: The user should be able to log in successfully using their Google account.
Actual Behavior: The message “Unable to get the public key” is displayed, preventing login.
Browser: Chrome 

![Screenshot_5](https://github.com/user-attachments/assets/260e6fb3-b0eb-4546-88bf-a053739c3026)

**Comment by arnob016** [comment] 2024-10-10 06:57
Duplicate of an issue reported by same issuer .

**Closed as completed** 2024-10-10 06:56 UTC
Labels: invalid
